### ISSUE TITLE
ITKSnap and RStudio 

### ISSUE THREAD

**Issue by rwickens** [CobraLab/MINC-VM#33] opened 2019-10-09 02:34 UTC
Hi there. I wanted to thank you for making this packer. I've run into two issues: 
- RStudio is a blank screen. I get an error relating to configuration: "failed to find matching FBconfig". 
- ITKsnap-3.4 does not work for me. I get the error: 
/usr/local/lib/snap-3.4.0/ITK-SNAP: error while loading shared libraries: libvtkChartsCore-6.2.so.6.2: cannot open shared object file: No such file or directory/

Any pointers would be helpful. 

Thanks,
Rebekah

**Comment by dorkylever** [comment] 2019-10-09 03:53
Hi Rebekah, 

Is the Rstudio blank screen something like this?: 
![image](https://user-images.githubusercontent.com/41981766/66450242-839a3100-eaa3-11e9-8319-3f94df02339f.png)

I remember using R-studio in the MINC-VM but I'm not sure what versions of Virtualbox and MINC-VM I used at the time.  What version of VirtualBox are you using? 

If you have an R-script can could launch it through R alone.

Kind Regards, 
Kyle Drover

**Comment by gdevenyi** [comment] 2019-10-10 19:52
Hi,

In order to address your issues, a number of additional pieces of information are needed
1. What version of Virtualbox are you using? The current version is built with 6.0.4
2. When did you get the VM (what date did you download and import)
3. What is the current state of your VM Settings -> Video -> 3D Acceleration settings.

As for itksnap, it appears that we can no longer supply the libraries needed for the binary version I included in the VM.

I don't know of a functional newer version, pinging @vfonov, is there an up-to-date itksnap-minc

**Comment by vfonov** [comment] 2019-10-10 19:54
I have slightly newer ITKSNAP in https://packages.bic.mni.mcgill.ca/minc-toolkit/third-party/

**Comment by gdevenyi** [comment] 2019-10-10 20:19
@vfonov looks like the latest Deb is missing hdf5_serial

**Comment by vfonov** [comment] 2019-10-10 20:37
that probably comes from the system package.

**Comment by rwickens** [comment] 2019-10-10 21:27
Hi, Thanks for the reply. I'm using VirtualBox 6.0.8. Perhaps I upgraded from 6.0.4 to 6.0.8 without thinking....
I downloaded the VM around July 2nd or so. I've attached a picture of my display settings.   
I will try to download the ITK-snap 3.6 from the website provided by vfononv. 
Best, Rebekah 
<img width="619" alt="Settings" src="https://user-images.githubusercontent.com/24905802/66607858-25dd1600-eb83-11e9-8703-0a4061894263.PNG">

**Comment by rwickens** [comment] 2019-10-10 21:44
When installing the ITK snap file suggested by @vfonov, it had issues building on the root directory. I don't appear to have permissions to access this directory. How should I modify permissions, or are these hard-set by the packer?  

<img width="532" alt="cannot_build_on_root_directory" src="https://user-images.githubusercontent.com/24905802/66608807-6dfd3800-eb85-11e9-9cb8-7e2f96e20d88.PNG">

**Comment by gdevenyi** [comment] 2019-10-10 21:45
This is like any other Linux system, you're an unprivileged user. You can use sudo with the password "minc" to do admin steps.

**Comment by rwickens** [comment] 2019-10-10 22:18
Ah, apologies. I've tried again with sudo gdebi. It installed, but I cannot access it in the terminal using commands "itksnap", "itksnap-minc", etc. 
Is this to be expected? 
<img width="833" alt="itksnap" src="https://user-images.githubusercontent.com/24905802/66610656-45c40800-eb8a-11e9-9228-0fed0bb35a28.PNG">

**Comment by gdevenyi** [comment] 2019-10-11 13:01
The package does not encode its dependencies, so it still doesn't work, I don't know what it depends on, so until I have time to investigate this further, I can't help there. I cannot support a modified VM with custom software so for now you'll have to wait for me to sort out how to get things working in an official release. I encourage you to investigate your VirtualBox version differences and whether the 3D acceleration switch can solve your issues.

**Comment by vfonov** [comment] 2019-10-11 13:58
try installing vtk 6.2

**Comment by vfonov** [comment] 2019-10-11 13:58
also, it seems that you are still running itksnap 3.4

**Comment by gdevenyi** [comment] 2019-10-11 20:05
I have confirmed as per my instructions that the black screen is fixed by disabling the 3D acceleration.

A new release will fix ITKsnap when I have time.

**Closed as completed by gdevenyi** 2019-10-11 20:05 UTC

**Comment by gdevenyi** [comment] 2019-10-11 20:22
@vfonov if you could share with me your build bits for the itksnap-minc I can try and automate a build/package to integrate here.

**Comment by rwickens** [comment] 2019-10-12 00:28
Thank you, @gdevenyi , changing the 3D acceleration fixed the RStudio issue completely. Apologies that I hadn't read your instructions carefully to catch that. Best, Rebekah

**Comment by gdevenyi** [comment] 2019-10-12 00:32
The next release will test the new VirtualBox driver with the hopes that it will fix this issue. Otherwise I'll disable this setting by default since it seems to break regularly.

**Comment by gdevenyi** [comment] 2019-10-16 17:04
Newly uploaded version has been rebuilt with 6.0.12 and with the "new" virtualbox video drivers. ITKSnap is still broken until I can the patch info from @vfonov and perhaps do a static build, or automate it against the release debs for minc-toolkit

**Comment by rwickens** [comment] 2019-11-16 17:04
@vfonov I have downloaded VTK 6.2 and have tried moving the charts-core contents to various folders within the ITKsnap 3.4 folder so that it finds it, including in ITK's core folder. I haven't had any luck. Any ideas on the precise locations it needs to be in?

**Comment by vfonov** [comment] 2019-11-16 19:49
should be installed in the system (apt-get install vtk....)

**Comment by gdevenyi** [comment] 2019-11-26 14:25
The current version of ubuntu that this VM is built with does not have the versions of VTK/ITK to support the ITKSnap version available as a binary release.

@vfonov if you can point me at your patches I can try and build a new version and/or see about getting them upstreamed.

**Comment by vfonov** [comment] 2019-11-26 17:22
https://github.com/vfonov/itksnap3
